services:
  chromium:
    image: ghcr.io/browserless/chromium:latest
    ports:
      - chromium>3000:3000
    restart: unless-stopped
    environment:
      TIMEOUT: "30000"
      CONCURRENT: "5"
      TOKEN: "${TOKEN}"
